MáDaBa csapat jótanácsai.
bmeaut/snippets pull request #59
Opened 2018-12-08 00:13 UTC by Strabi1

MáDaBa csapat jótanácsai az utókornak.  :)

2018-12-08 00:13 UTC, Strabi1 commented
a

2018-12-10 11:01 UTC, csorbakristof requested changes
OK, csak a sorszámát és a kódnevet kérlek írjátok át 37-esre, mert egyszerre többen választottátok ugyanazt a sorszámot.

2018-12-10 11:07 UTC, csorbakristof requested changes
A codename a fájl elején még 30-as...

2018-12-10 11:07 UTC, csorbakristof commented on snippets/AlkFejlHfTanulsagok/37/index.md
> +codename: AlkFejlHf30
Itt még 30-as sorszám szerepel...

2018-12-11 12:44 UTC, csorbakristof approved these changes

2018-12-11 12:44 UTC, merged

2018-12-11 12:45 UTC, csorbakristof commented
OK, köszönöm!