A Glitter csapat tapasztalatai.
bmeaut/snippets pull request #60
Opened 2018-12-08 14:15 UTC by nagytibi

A Glitter csapat tapasztalatai.

2018-12-10 11:00 UTC, csorbakristof requested changes
A könyvtárat és a kódnevet kérlek, írjátok át 36-ra (többen egyszerre választottátok a 32-t.) Egyébként OK lesz.

2018-12-10 15:44 UTC, nagytibi reviewed
Javítva a snippet sorszám 32-ről 36-ra.

2018-12-11 12:45 UTC, csorbakristof approved these changes

2018-12-11 12:45 UTC, merged

2018-12-11 12:45 UTC, csorbakristof commented
OK, köszönöm!