Added snippets
bmeaut/snippets pull request #76
Opened 2019-12-13 11:31 UTC by FTim

2019-12-13 20:18 UTC, csorbakristof requested changes
Két apróság, bocs, ha kötözködősnek tűnik, nem az a cél... de utána mergelem. :)

2019-12-13 20:18 UTC, csorbakristof commented on snippets/0901_StopwatchVsDateTime/index.md
> +Ahogy láthatjuk, minnél rövidebb ideig tart egy művelet a DateTime annál pontatlanabb esz a Stopwatch-hoz képest. Tanulság: használjunk időmérésre Stopwatch-ot!
```suggestion
Ahogy láthatjuk, minnél rövidebb ideig tart egy művelet a DateTime annál pontatlanabb lesz a Stopwatch-hoz képest. Tanulság: használjunk időmérésre Stopwatch-ot!
```

2019-12-13 20:18 UTC, csorbakristof commented on snippets/0901_StopwatchVsDateTime/index.md
> +## DateTime.Now
Hogy a plain text is olvasható legyen, nem lenne jobb a fejlécek elé egy üres sor?

2019-12-15 17:33 UTC, FTim commented
Nem veszem kötözködésnek:)
Elírás javítva, fejlécek elé+után üres sorok beszúrva (minden snippetnél)

2019-12-17 14:03 UTC, merged

2019-12-17 14:03 UTC, csorbakristof commented
Szuper, köszönöm!